import { ProgressLog } from '@/types/progress'

// Mock Progress Logs per sviluppo
export const mockProgressLogs: ProgressLog[] = [
  {
    id: '1',
    athlete_id: 'athlete-1',
    date: '2024-12-15',
    weight_kg: 82.5,
    max_bench_kg: 80,
    max_squat_kg: 120,
    max_deadlift_kg: 140,
    note: 'Ottima settimana di allenamento',
    mood_text: '💪',
    created_at: '2024-12-15T10:00:00Z',
  },
  {
    id: '2',
    athlete_id: 'athlete-1',
    date: '2024-12-22',
    weight_kg: 81.8,
    max_bench_kg: 82.5,
    max_squat_kg: 122.5,
    max_deadlift_kg: 142.5,
    note: 'Nuovo PR su panca!',
    mood_text: '🔥',
    created_at: '2024-12-22T10:00:00Z',
  },
  {
    id: '3',
    athlete_id: 'athlete-1',
    date: '2024-12-29',
    weight_kg: 81.2,
    max_bench_kg: 85,
    max_squat_kg: 125,
    max_deadlift_kg: 145,
    note: 'Continuo a migliorare',
    mood_text: '😊',
    created_at: '2024-12-29T10:00:00Z',
  },
  {
    id: '4',
    athlete_id: 'athlete-1',
    date: '2025-01-05',
    weight_kg: 80.5,
    max_bench_kg: 87.5,
    max_squat_kg: 127.5,
    max_deadlift_kg: 147.5,
    note: 'Peso in calo, forza in aumento!',
    mood_text: '💪',
    created_at: '2025-01-05T10:00:00Z',
  },
  {
    id: '5',
    athlete_id: 'athlete-1',
    date: '2025-01-10',
    weight_kg: 79.8,
    max_bench_kg: 90,
    max_squat_kg: 130,
    max_deadlift_kg: 150,
    note: 'Nuovo PR su tutti gli esercizi! 🎉',
    mood_text: '🔥',
    created_at: '2025-01-10T10:00:00Z',
  },
]

// Mock KPI Data
import type { ProgressKPI } from '@/hooks/use-progress-analytics'

export const mockProgressKPI: ProgressKPI = {
  pesoAttuale: 79.8,
  variazionePeso7gg: -0.7,
  forzaMassima: 150,
  percentualeCompletamento: 85,
  streak: 7,
  datasetPeso: [
    { date: '2024-12-15', peso: 82.5 },
    { date: '2024-12-22', peso: 81.8 },
    { date: '2024-12-29', peso: 81.2 },
    { date: '2025-01-05', peso: 80.5 },
    { date: '2025-01-10', peso: 79.8 },
  ],
  datasetForza: [
    { date: '2024-12-15', forza: 140 },
    { date: '2024-12-22', forza: 142.5 },
    { date: '2024-12-29', forza: 145 },
    { date: '2025-01-05', forza: 147.5 },
    { date: '2025-01-10', forza: 150 },
  ],
  datasetCompletamento: [
    { date: '2024-12-09', percentuale: 75 },
    { date: '2024-12-16', percentuale: 80 },
    { date: '2024-12-23', percentuale: 90 },
    { date: '2024-12-30', percentuale: 85 },
  ],
  ultimiProgressi: mockProgressLogs.map((log) => ({
    id: log.id,
    date: log.date,
    weight_kg: log.weight_kg ?? null,
    max_bench_kg: log.max_bench_kg ?? null,
    max_squat_kg: log.max_squat_kg ?? null,
    max_deadlift_kg: log.max_deadlift_kg ?? null,
    note: log.note ?? null,
  })),
  // Composizione corporea
  datasetComposizioneCorporea: [
    {
      date: '2024-12-15',
      massa_grassa_percentuale: 15.5,
      massa_grassa_kg: 12.8,
      massa_magra_kg: 69.7,
      massa_muscolare_kg: 58.2,
      massa_muscolare_scheletrica_kg: 30.5,
    },
    {
      date: '2024-12-22',
      massa_grassa_percentuale: 15.2,
      massa_grassa_kg: 12.4,
      massa_magra_kg: 69.4,
      massa_muscolare_kg: 58.5,
      massa_muscolare_scheletrica_kg: 30.7,
    },
    {
      date: '2024-12-29',
      massa_grassa_percentuale: 14.9,
      massa_grassa_kg: 12.1,
      massa_magra_kg: 69.1,
      massa_muscolare_kg: 58.8,
      massa_muscolare_scheletrica_kg: 30.9,
    },
    {
      date: '2025-01-05',
      massa_grassa_percentuale: 14.6,
      massa_grassa_kg: 11.8,
      massa_magra_kg: 68.7,
      massa_muscolare_kg: 59.1,
      massa_muscolare_scheletrica_kg: 31.1,
    },
    {
      date: '2025-01-10',
      massa_grassa_percentuale: 14.3,
      massa_grassa_kg: 11.4,
      massa_magra_kg: 68.4,
      massa_muscolare_kg: 59.4,
      massa_muscolare_scheletrica_kg: 31.3,
    },
  ],
  valoriComposizioneAttuali: {
    massa_grassa_percentuale: 14.3,
    massa_grassa_kg: 11.4,
    massa_magra_kg: 68.4,
    massa_muscolare_kg: 59.4,
    massa_muscolare_scheletrica_kg: 31.3,
    rapporto_massa_magra_peso: 0.857,
  },
  // Circonferenze
  datasetCirconferenze: [
    {
      date: '2024-12-15',
      braccio_contratto_cm: 38.5,
      braccio_rilassato_cm: null,
      avambraccio_cm: null,
      collo_cm: null,
      spalle_cm: 115,
      torace_cm: 105,
      torace_inspirazione_cm: null,
      vita_cm: 82,
      vita_alta_cm: null,
      addome_basso_cm: 85,
      fianchi_cm: 95,
      glutei_cm: 98,
      coscia_alta_cm: null,
      coscia_media_cm: 62,
      coscia_bassa_cm: null,
      ginocchio_cm: null,
      polpaccio_cm: 38,
      caviglia_cm: null,
      polso_cm: null,
      biceps_cm: null,
    },
    {
      date: '2024-12-22',
      braccio_contratto_cm: 38.7,
      braccio_rilassato_cm: null,
      avambraccio_cm: null,
      collo_cm: null,
      spalle_cm: 115.5,
      torace_cm: 105.5,
      torace_inspirazione_cm: null,
      vita_cm: 81.5,
      vita_alta_cm: null,
      addome_basso_cm: 84.5,
      fianchi_cm: 94.5,
      glutei_cm: 98.5,
      coscia_alta_cm: null,
      coscia_media_cm: 62.2,
      coscia_bassa_cm: null,
      ginocchio_cm: null,
      polpaccio_cm: 38.2,
      caviglia_cm: null,
      polso_cm: null,
      biceps_cm: null,
    },
    {
      date: '2024-12-29',
      braccio_contratto_cm: 38.9,
      braccio_rilassato_cm: null,
      avambraccio_cm: null,
      collo_cm: null,
      spalle_cm: 116,
      torace_cm: 106,
      torace_inspirazione_cm: null,
      vita_cm: 81,
      vita_alta_cm: null,
      addome_basso_cm: 84,
      fianchi_cm: 94,
      glutei_cm: 99,
      coscia_alta_cm: null,
      coscia_media_cm: 62.4,
      coscia_bassa_cm: null,
      ginocchio_cm: null,
      polpaccio_cm: 38.4,
      caviglia_cm: null,
      polso_cm: null,
      biceps_cm: null,
    },
    {
      date: '2025-01-05',
      braccio_contratto_cm: 39.1,
      braccio_rilassato_cm: null,
      avambraccio_cm: null,
      collo_cm: null,
      spalle_cm: 116.5,
      torace_cm: 106.5,
      torace_inspirazione_cm: null,
      vita_cm: 80.5,
      vita_alta_cm: null,
      addome_basso_cm: 83.5,
      fianchi_cm: 93.5,
      glutei_cm: 99.5,
      coscia_alta_cm: null,
      coscia_media_cm: 62.6,
      coscia_bassa_cm: null,
      ginocchio_cm: null,
      polpaccio_cm: 38.6,
      caviglia_cm: null,
      polso_cm: null,
      biceps_cm: null,
    },
    {
      date: '2025-01-10',
      braccio_contratto_cm: 39.3,
      braccio_rilassato_cm: null,
      avambraccio_cm: null,
      collo_cm: null,
      spalle_cm: 117,
      torace_cm: 107,
      torace_inspirazione_cm: null,
      vita_cm: 80,
      vita_alta_cm: null,
      addome_basso_cm: 83,
      fianchi_cm: 93,
      glutei_cm: 100,
      coscia_alta_cm: null,
      coscia_media_cm: 62.8,
      coscia_bassa_cm: null,
      ginocchio_cm: null,
      polpaccio_cm: 38.8,
      caviglia_cm: null,
      polso_cm: null,
      biceps_cm: null,
    },
  ],
  valoriCirconferenzeAttuali: {
    braccio_contratto_cm: 39.3,
    braccio_rilassato_cm: null,
    avambraccio_cm: null,
    collo_cm: null,
    spalle_cm: 117,
    torace_cm: 107,
    torace_inspirazione_cm: null,
    vita_cm: 80,
    vita_alta_cm: null,
    addome_basso_cm: 83,
    fianchi_cm: 93,
    glutei_cm: 100,
    coscia_alta_cm: null,
    coscia_media_cm: 62.8,
    coscia_bassa_cm: null,
    ginocchio_cm: null,
    polpaccio_cm: 38.8,
    caviglia_cm: null,
    polso_cm: null,
    biceps_cm: null,
  },
  // Forza dettagliata
  datasetForzaDettagliata: [
    { date: '2024-12-15', max_bench_kg: 80, max_squat_kg: 120, max_deadlift_kg: 140 },
    { date: '2024-12-22', max_bench_kg: 82.5, max_squat_kg: 122.5, max_deadlift_kg: 142.5 },
    { date: '2024-12-29', max_bench_kg: 85, max_squat_kg: 125, max_deadlift_kg: 145 },
    { date: '2025-01-05', max_bench_kg: 87.5, max_squat_kg: 127.5, max_deadlift_kg: 147.5 },
    { date: '2025-01-10', max_bench_kg: 90, max_squat_kg: 130, max_deadlift_kg: 150 },
  ],
  valoriForzaAttuali: {
    max_bench_kg: 90,
    max_squat_kg: 130,
    max_deadlift_kg: 150,
  },
}
