'use client'

import { useCallback, useEffect, useState, useMemo, memo } from 'react'
import { useSearchParams } from 'next/navigation'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import {
  ClipboardList,
  ArrowRight,
  User,
  FilePlus,
  Copy,
  Download,
  Filter,
  Search,
  X,
  MoreVertical,
  FileText,
  Sparkles,
  CalendarClock,
  AlertCircle,
  Mail,
  Upload,
  Loader2,
  Pencil,
  Trash2,
} from 'lucide-react'
import { useStaffDashboardGuard } from '@/hooks/use-staff-dashboard-guard'
import { useAuth } from '@/hooks/use-auth'
import { useSupabaseClient } from '@/hooks/use-supabase-client'
import {
  Button,
  Input,
  Label,
  Drawer,
  DrawerContent,
  DrawerHeader,
  DrawerBody,
  DropdownMenu,
  DropdownMenuTrigger,
  DropdownMenuContent,
  DropdownMenuItem,
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from '@/components/ui'
import { StaffContentLayout } from '@/components/shared/dashboard/staff-content-layout'
import { createLogger } from '@/lib/logger'
import {
  NUTRITION_TABLES,
  nutritionFrom,
  STAFF_ASSIGNMENT_STATUS_ACTIVE,
  STAFF_TYPE_NUTRIZIONISTA,
  PLAN_VERSION_STATUS_ACTIVE,
  PLAN_VERSION_STATUS_DRAFT,
  PLAN_VERSION_STATUS_ARCHIVED,
} from '@/lib/nutrition-tables'
import { chunkForSupabaseIn } from '@/lib/supabase/in-query-chunks'
import { buildTabularExportPdfBlob, type ExportData } from '@/lib/export-utils'
import { usePdfPreviewDialog } from '@/hooks/use-pdf-preview-dialog'
import { PdfCanvasPreviewDialog } from '@/components/shared/pdf-canvas-preview-dialog'
import { downloadStorageBlobViaPreview, storagePreviewHref } from '@/lib/documents'

const logger = createLogger('app:dashboard:nutrizionista:piani')
const LOADING_CLASS = 'flex min-h-[50vh] items-center justify-center bg-background'
const DEBOUNCE_MS = 300
/** DB può usare 'published' per piani attivi; consideriamo entrambi come attivi in UI */
const isPlanVersionActive = (status: string) =>
  status === PLAN_VERSION_STATUS_ACTIVE || status === 'published'

type VersionRow = {
  groupId: string
  athleteId: string
  athleteName: string
  athleteEmail: string | null
  versionId: string
  versionNumber: number | null
  status: string
  startDate: string | null
  endDate: string | null
  createdAt: string | null
  caloriesTarget: number | null
  proteinTarget: number | null
  carbTarget: number | null
  fatTarget: number | null
  pdfFilePath: string | null
  autoGenerated: boolean | null
  autoAdjustmentReason: string | null
  /** true se riga da Storage (PDF non assegnato) */
  isUnassigned?: boolean
  /** Nome file per documenti non assegnati */
  fileName?: string
  /** Path Storage per download (es. nutrition-plans/_unassigned/xxx/file.pdf) */
  storagePath?: string
}

type SortOption = 'updated' | 'scadenza' | 'atleta' | 'versione'
const SORT_OPTIONS: { value: SortOption; label: string }[] = [
  { value: 'updated', label: 'Ultima modifica' },
  { value: 'scadenza', label: 'Scadenza (più vicina)' },
  { value: 'atleta', label: 'Atleta (A-Z)' },
  { value: 'versione', label: 'Versione (desc)' },
]

function useDebounce<T>(value: T, delay: number): T {
  const [debouncedValue, setDebouncedValue] = useState(value)
  useEffect(() => {
    const t = setTimeout(() => setDebouncedValue(value), delay)
    return () => clearTimeout(t)
  }, [value, delay])
  return debouncedValue
}

function KpiCard({
  label,
  value,
  active,
  onClick,
  icon: Icon,
}: {
  label: string
  value: number
  active?: boolean
  onClick?: () => void
  icon: React.ElementType
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      className={`rounded-xl border p-3 sm:p-5 text-left min-w-0 min-h-[44px] touch-manipulation transition-colors ${
        active
          ? 'border-teal-500/50 bg-teal-500/10 ring-1 ring-teal-500/30'
          : 'border-border bg-background-secondary/80 ring-1 ring-white/5 hover:bg-background-tertiary/50'
      }`}
    >
      <div className="flex items-center gap-2 text-text-secondary text-xs mb-0.5">
        <Icon className="h-4 w-4 shrink-0" />
        {label}
      </div>
      <p className="text-xl font-bold text-text-primary tabular-nums">{value}</p>
    </button>
  )
}

const VersionRowActions = memo(function VersionRowActions({
  row,
  onViewReason,
}: {
  row: VersionRow
  onViewReason: (row: VersionRow) => void
}) {
  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="ghost" size="icon" className="h-9 w-9 shrink-0" aria-label="Azioni">
          <MoreVertical className="h-4 w-4" />
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end">
        <DropdownMenuItem asChild>
          <Link href={`/dashboard/nutrizionista/atleti/${row.athleteId}?tab=piani`}>
            <User className="mr-2 h-4 w-4" />
            Apri dettaglio
          </Link>
        </DropdownMenuItem>
        <DropdownMenuItem asChild>
          <Link href={`/dashboard/nutrizionista/atleti/${row.athleteId}?tab=piani`}>
            <Copy className="mr-2 h-4 w-4" />
            Duplica versione
          </Link>
        </DropdownMenuItem>
        <DropdownMenuItem asChild>
          <Link href={`/dashboard/nutrizionista/atleti/${row.athleteId}?tab=struttura`}>
            Modifica struttura
          </Link>
        </DropdownMenuItem>
        <DropdownMenuItem disabled>
          <FileText className="mr-2 h-4 w-4" />
          Genera PDF
        </DropdownMenuItem>
        {row.autoAdjustmentReason && (
          <DropdownMenuItem onClick={() => onViewReason(row)}>
            <Sparkles className="mr-2 h-4 w-4" />
            Vedi reason
          </DropdownMenuItem>
        )}
      </DropdownMenuContent>
    </DropdownMenu>
  )
})

export default function NutrizionistaPianiPage() {
  const router = useRouter()
  const searchParams = useSearchParams()
  const filterParam = searchParams.get('filter')
  const { showLoader } = useStaffDashboardGuard('nutrizionista')
  const { user, org_id: orgId } = useAuth()
  const supabase = useSupabaseClient()
  const profileId = user?.id ?? null
  const {
    open: pdfOpen,
    blob: pdfBlob,
    filename: pdfFilename,
    loading: pdfLoading,
    setLoading: setPdfLoading,
    openWithBlob: openPdfWithBlob,
    onOpenChange: onPdfOpenChange,
  } = usePdfPreviewDialog()

  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [rows, setRows] = useState<VersionRow[]>([])
  const [searchInput, setSearchInput] = useState('')
  const [sortBy, setSortBy] = useState<SortOption>('updated')
  const [filtersOpen, setFiltersOpen] = useState(false)
  const [kpiFilter, setKpiFilter] = useState<string | null>(() =>
    filterParam === 'scadenza' ? 'scadenza' : null,
  )
  const [filterStato, setFilterStato] = useState<'all' | 'draft' | 'active' | 'archived'>('all')
  const [filterScadenza, setFilterScadenza] = useState<'all' | '7' | '30' | 'scaduto'>('all')
  const [filterAuto, setFilterAuto] = useState<'all' | 'si' | 'no'>('all')
  const [nuovoPianoOpen, setNuovoPianoOpen] = useState(false)
  const [nuovaVersioneOpen, setNuovaVersioneOpen] = useState(false)
  const [reasonModalRow, setReasonModalRow] = useState<VersionRow | null>(null)
  const [assignedAthletes, setAssignedAthletes] = useState<{ id: string; name: string }[]>([])
  const [caricaPianoOpen, setCaricaPianoOpen] = useState(false)
  const [caricaPianoAthleteId, setCaricaPianoAthleteId] = useState('')
  const [caricaPianoFile, setCaricaPianoFile] = useState<File | null>(null)
  const [caricaPianoLoading, setCaricaPianoLoading] = useState(false)
  const [caricaPianoError, setCaricaPianoError] = useState<string | null>(null)
  const [unassignedRenameRow, setUnassignedRenameRow] = useState<VersionRow | null>(null)
  const [unassignedRenameValue, setUnassignedRenameValue] = useState('')
  const [unassignedRenameLoading, setUnassignedRenameLoading] = useState(false)
  const [unassignedAssignRow, setUnassignedAssignRow] = useState<VersionRow | null>(null)
  const [unassignedAssignAthleteId, setUnassignedAssignAthleteId] = useState('')
  const [unassignedAssignLoading, setUnassignedAssignLoading] = useState(false)
  const [unassignedAssignError, setUnassignedAssignError] = useState<string | null>(null)
  const [unassignedDeleteRow, setUnassignedDeleteRow] = useState<VersionRow | null>(null)
  const [unassignedDeleteLoading, setUnassignedDeleteLoading] = useState(false)
  const [validityEditRow, setValidityEditRow] = useState<VersionRow | null>(null)
  const [validityEditStart, setValidityEditStart] = useState('')
  const [validityEditEnd, setValidityEditEnd] = useState('')
  const [validityEditLoading, setValidityEditLoading] = useState(false)

  const debouncedSearch = useDebounce(searchInput.trim().toLowerCase(), DEBOUNCE_MS)

  const loadData = useCallback(async () => {
    if (!profileId) {
      setRows([])
      setLoading(false)
      return
    }
    setLoading(true)
    setError(null)
    try {
      const { data: staffData, error: staffErr } = await supabase
        .from('staff_atleti')
        .select('atleta_id')
        .eq('staff_id', profileId)
        .eq('status', STAFF_ASSIGNMENT_STATUS_ACTIVE)
        .eq('staff_type', STAFF_TYPE_NUTRIZIONISTA)
      if (staffErr) throw staffErr
      const athleteIds = (staffData ?? [])
        .map((r) => (r as { atleta_id: string }).atleta_id)
        .filter(Boolean)

      const groupsRes = await nutritionFrom(supabase, NUTRITION_TABLES.planGroups)
        .select('id, athlete_id')
        .eq('nutrizionista_id', profileId)
      const groups = (groupsRes.data ?? []) as Array<{ id: string; athlete_id: string }>
      const groupIds = groups.map((g) => g.id)

      const athleteIdsFromGroups = [...new Set(groups.map((g) => g.athlete_id).filter(Boolean))]
      const allAthleteIds = [...new Set([...athleteIds, ...athleteIdsFromGroups])]
      const profilesAccum: {
        id: string
        nome: string | null
        cognome: string | null
        email: string | null
      }[] = []
      for (const idChunk of chunkForSupabaseIn(allAthleteIds)) {
        const { data: profilesData } = await supabase
          .from('profiles')
          .select('id, nome, cognome, email')
          .in('id', idChunk)
        profilesAccum.push(...((profilesData ?? []) as (typeof profilesAccum)[number][]))
      }
      const profilesMap = new Map(
        profilesAccum.map((p) => [
          p.id,
          {
            name: [p.nome, p.cognome].filter(Boolean).join(' ') || p.id.slice(0, 8),
            email: p.email ?? null,
          },
        ]),
      )
      setAssignedAthletes(
        athleteIds.map((id) => ({ id, name: profilesMap.get(id)?.name ?? id.slice(0, 8) })),
      )

      let list: VersionRow[] = []
      if (groupIds.length > 0) {
        type Ver = {
          id: string
          plan_id?: string
          version_number: number | null
          status: string
          start_date: string | null
          end_date: string | null
          created_at: string | null
          calories_target?: number | null
          protein_target?: number | null
          carb_target?: number | null
          fat_target?: number | null
          pdf_file_path?: string | null
          auto_generated?: boolean | null
          auto_adjustment_reason?: string | null
        }
        const versions: Ver[] = []
        for (const gidChunk of chunkForSupabaseIn(groupIds)) {
          const verRes = await nutritionFrom(supabase, NUTRITION_TABLES.planVersions)
            .select(
              'id, plan_id, version_number, status, start_date, end_date, created_at, calories_target, protein_target, carb_target, fat_target, pdf_file_path, auto_generated, auto_adjustment_reason',
            )
            .in('plan_id', gidChunk)
            .order('created_at', { ascending: false })
          versions.push(...((verRes.data ?? []) as Ver[]))
        }
        versions.sort(
          (a, b) => new Date(b.created_at ?? 0).getTime() - new Date(a.created_at ?? 0).getTime(),
        )
        const athleteByGroupId = new Map(groups.map((g) => [g.id, g.athlete_id]))
        list = versions.map((v) => {
          const gid = v.plan_id ?? ''
          const aid = athleteByGroupId.get(gid) ?? ''
          const prof = profilesMap.get(aid)
          return {
            groupId: gid,
            athleteId: aid,
            athleteName: prof?.name ?? aid.slice(0, 8),
            athleteEmail: prof?.email ?? null,
            versionId: v.id,
            versionNumber: v.version_number,
            status: v.status,
            startDate: v.start_date,
            endDate: v.end_date,
            createdAt: v.created_at,
            caloriesTarget: v.calories_target ?? null,
            proteinTarget: v.protein_target ?? null,
            carbTarget: v.carb_target ?? null,
            fatTarget: v.fat_target ?? null,
            pdfFilePath: v.pdf_file_path ?? null,
            autoGenerated: v.auto_generated ?? null,
            autoAdjustmentReason: v.auto_adjustment_reason ?? null,
          }
        })
      }

      const unassignedPath = `nutrition-plans/_unassigned/${profileId}`
      const { data: storageFiles } = await supabase.storage.from('documents').list(unassignedPath)
      const storageRows: VersionRow[] = (storageFiles ?? [])
        .filter(
          (f) =>
            (f as { name?: string }).name &&
            (f as { name: string }).name.toLowerCase().endsWith('.pdf'),
        )
        .map((f) => {
          const name = (f as { name: string }).name
          const updated =
            (f as { updated_at?: string }).updated_at ?? (f as { created_at?: string }).created_at
          const path = `${unassignedPath}/${name}`
          return {
            groupId: '',
            athleteId: '',
            athleteName: 'Non assegnato',
            athleteEmail: null,
            versionId: `storage-${path}`,
            versionNumber: null,
            status: '—',
            startDate: null,
            endDate: null,
            createdAt: updated ?? null,
            caloriesTarget: null,
            proteinTarget: null,
            carbTarget: null,
            fatTarget: null,
            pdfFilePath: path,
            autoGenerated: null,
            autoAdjustmentReason: null,
            isUnassigned: true,
            fileName: name,
            storagePath: path,
          }
        })

      const nutritionPlansPrefix = 'nutrition-plans'
      const { data: planFolders } = await supabase.storage
        .from('documents')
        .list(nutritionPlansPrefix)
      const assignedStorageRows: VersionRow[] = []
      const folderNames = (planFolders ?? [])
        .map((f) => (f as { name?: string }).name)
        .filter((n): n is string => !!n && n !== '_unassigned' && /^[0-9a-f-]{36}$/i.test(n))
      if (folderNames.length > 0) {
        const athleteProfilesMerged: {
          id: string
          nome: string | null
          cognome: string | null
          email: string | null
        }[] = []
        for (const idChunk of chunkForSupabaseIn(folderNames)) {
          const { data: athleteProfiles } = await supabase
            .from('profiles')
            .select('id, nome, cognome, email')
            .in('id', idChunk)
          athleteProfilesMerged.push(
            ...((athleteProfiles ?? []) as (typeof athleteProfilesMerged)[number][]),
          )
        }
        const athleteNameById = new Map(
          athleteProfilesMerged.map(
            (p: {
              id: string
              nome: string | null
              cognome: string | null
              email: string | null
            }) => [p.id, [p.nome, p.cognome].filter(Boolean).join(' ').trim() || p.id.slice(0, 8)],
          ),
        )
        const athleteEmailById = new Map(
          athleteProfilesMerged.map((p: { id: string; email: string | null }) => [
            p.id,
            p.email ?? null,
          ]),
        )
        for (const athleteId of folderNames) {
          const { data: files } = await supabase.storage
            .from('documents')
            .list(`${nutritionPlansPrefix}/${athleteId}`)
          const pdfs = (files ?? []).filter(
            (f) =>
              (f as { name?: string }).name &&
              (f as { name: string }).name.toLowerCase().endsWith('.pdf'),
          )
          for (const f of pdfs) {
            const name = (f as { name: string }).name
            const updated =
              (f as { updated_at?: string }).updated_at ?? (f as { created_at?: string }).created_at
            const path = `${nutritionPlansPrefix}/${athleteId}/${name}`
            assignedStorageRows.push({
              groupId: '',
              athleteId,
              athleteName: athleteNameById.get(athleteId) ?? athleteId.slice(0, 8),
              athleteEmail: athleteEmailById.get(athleteId) ?? null,
              versionId: `storage-${path}`,
              versionNumber: null,
              status: '—',
              startDate: null,
              endDate: null,
              createdAt: updated ?? null,
              caloriesTarget: null,
              proteinTarget: null,
              carbTarget: null,
              fatTarget: null,
              pdfFilePath: path,
              autoGenerated: null,
              autoAdjustmentReason: null,
              isUnassigned: false,
              fileName: name,
              storagePath: path,
            })
          }
        }
      }

      const merged = [...list, ...assignedStorageRows, ...storageRows].sort((a, b) => {
        const ca = a.createdAt ?? ''
        const cb = b.createdAt ?? ''
        return cb.localeCompare(ca)
      })
      setRows(merged)
    } catch (e) {
      logger.error('Errore caricamento piani', e)
      setError(e instanceof Error ? e.message : 'Errore caricamento')
    } finally {
      setLoading(false)
    }
  }, [profileId, supabase])

  useEffect(() => {
    void loadData()
  }, [loadData])

  const today = useMemo(() => new Date(), [])
  const todayStr = today.toISOString().slice(0, 10)
  const in7 = useMemo(() => {
    const d = new Date(today)
    d.setDate(d.getDate() + 7)
    return d.toISOString().slice(0, 10)
  }, [today])
  const in30 = useMemo(() => {
    const d = new Date(today)
    d.setDate(d.getDate() + 30)
    return d.toISOString().slice(0, 10)
  }, [today])

  const isRowActive = useCallback(
    (r: VersionRow) => isPlanVersionActive(r.status) || !!r.storagePath,
    [],
  )
  const kpiCounts = useMemo(() => {
    const attivi = rows.filter((r) => isRowActive(r)).length
    const bozze = rows.filter((r) => r.status === PLAN_VERSION_STATUS_DRAFT).length
    const inScadenza = rows.filter(
      (r) => r.endDate && r.endDate >= todayStr && r.endDate <= in7,
    ).length
    const scaduti = rows.filter((r) => r.endDate && r.endDate < todayStr).length
    const autoGen = rows.filter((r) => r.autoGenerated === true).length
    return { attivi, bozze, inScadenza, scaduti, autoGen }
  }, [rows, todayStr, in7, isRowActive])

  const filteredAndSorted = useMemo(() => {
    let list = rows

    if (debouncedSearch) {
      list = list.filter(
        (r) =>
          (r.athleteName ?? '').toLowerCase().includes(debouncedSearch) ||
          (r.athleteEmail ?? '').toLowerCase().includes(debouncedSearch) ||
          (r.autoAdjustmentReason ?? '').toLowerCase().includes(debouncedSearch) ||
          (r.fileName ?? '').toLowerCase().includes(debouncedSearch),
      )
    }

    if (kpiFilter === 'attivi') list = list.filter((r) => isRowActive(r))
    else if (kpiFilter === 'bozze')
      list = list.filter((r) => r.status === PLAN_VERSION_STATUS_DRAFT)
    else if (kpiFilter === 'scadenza') {
      list = list.filter((r) => r.endDate && r.endDate >= todayStr && r.endDate <= in7)
    } else if (kpiFilter === 'scaduti') {
      list = list.filter((r) => r.endDate && r.endDate < todayStr)
    } else if (kpiFilter === 'auto') {
      list = list.filter((r) => r.autoGenerated === true)
    }

    if (filterStato !== 'all') {
      list = list.filter((r) => {
        if (filterStato === 'draft') return r.status === PLAN_VERSION_STATUS_DRAFT
        if (filterStato === 'active') return isRowActive(r)
        if (filterStato === 'archived') return r.status === PLAN_VERSION_STATUS_ARCHIVED
        return true
      })
    }
    if (filterScadenza === '7') {
      list = list.filter((r) => r.endDate && r.endDate >= todayStr && r.endDate <= in7)
    } else if (filterScadenza === '30') {
      list = list.filter((r) => r.endDate && r.endDate >= todayStr && r.endDate <= in30)
    } else if (filterScadenza === 'scaduto') {
      list = list.filter((r) => r.endDate && r.endDate < todayStr)
    }
    if (filterAuto === 'si') list = list.filter((r) => r.autoGenerated === true)
    else if (filterAuto === 'no') list = list.filter((r) => r.autoGenerated !== true)

    const sorted = [...list].sort((a, b) => {
      if (sortBy === 'atleta') return (a.athleteName ?? '').localeCompare(b.athleteName ?? '')
      if (sortBy === 'versione') return (b.versionNumber ?? 0) - (a.versionNumber ?? 0)
      if (sortBy === 'scadenza') {
        const da = a.endDate ?? '9999-99-99'
        const db = b.endDate ?? '9999-99-99'
        return da.localeCompare(db)
      }
      const ca = a.createdAt ?? ''
      const cb = b.createdAt ?? ''
      return cb.localeCompare(ca)
    })
    return sorted
  }, [
    rows,
    debouncedSearch,
    kpiFilter,
    filterStato,
    filterScadenza,
    filterAuto,
    sortBy,
    todayStr,
    in7,
    in30,
    isRowActive,
  ])

  const hasActiveFilters =
    kpiFilter ||
    filterStato !== 'all' ||
    filterScadenza !== 'all' ||
    filterAuto !== 'all' ||
    debouncedSearch

  const handleCaricaPiano = useCallback(async () => {
    if (!caricaPianoFile || !profileId) {
      setCaricaPianoError('Seleziona un file PDF.')
      return
    }
    if (!caricaPianoFile.name.toLowerCase().endsWith('.pdf')) {
      setCaricaPianoError('Il file deve essere in formato PDF.')
      return
    }
    if (caricaPianoAthleteId && !orgId) {
      setCaricaPianoError('Profilo senza organizzazione.')
      return
    }
    setCaricaPianoLoading(true)
    setCaricaPianoError(null)
    try {
      const ext = caricaPianoFile.name.split('.').pop() || 'pdf'
      const fileName = `${Date.now()}-${Math.random().toString(36).slice(2, 9)}.${ext}`
      const folder = caricaPianoAthleteId || `_unassigned/${profileId}`
      const filePath = `nutrition-plans/${folder}/${fileName}`
      const { error: uploadErr } = await supabase.storage
        .from('documents')
        .upload(filePath, caricaPianoFile, { cacheControl: '3600', upsert: false })
      if (uploadErr) throw uploadErr
      const { data: urlData } = supabase.storage.from('documents').getPublicUrl(filePath)
      const pdfUrl = urlData.publicUrl

      if (caricaPianoAthleteId && orgId) {
        let groupId: string
        const { data: existingGroup } = await nutritionFrom(supabase, NUTRITION_TABLES.planGroups)
          .select('id')
          .eq('athlete_id', caricaPianoAthleteId)
          .limit(1)
          .maybeSingle()
        const groupRow = existingGroup as { id: string } | null
        if (groupRow?.id) {
          groupId = groupRow.id
        } else {
          const { data: newGroup, error: groupErr } = await nutritionFrom(
            supabase,
            NUTRITION_TABLES.planGroups,
          )
            .insert({
              athlete_id: caricaPianoAthleteId,
              org_id: orgId,
              nutrizionista_id: profileId,
            } as Record<string, unknown>)
            .select('id')
            .single()
          if (groupErr || !newGroup) throw groupErr ?? new Error('Errore creazione gruppo')
          groupId = (newGroup as { id: string }).id
        }
        const { data: maxVer } = await nutritionFrom(supabase, NUTRITION_TABLES.planVersions)
          .select('version_number')
          .eq('plan_id', groupId)
          .order('version_number', { ascending: false })
          .limit(1)
          .maybeSingle()
        const nextVersion =
          (maxVer as { version_number: number | null } | null)?.version_number ?? 0
        const today = new Date().toISOString().slice(0, 10)
        const { error: versionErr } = await nutritionFrom(
          supabase,
          NUTRITION_TABLES.planVersions,
        ).insert({
          plan_id: groupId,
          org_id: orgId,
          version_number: nextVersion + 1,
          status: 'published',
          start_date: today,
          end_date: today,
          created_by: profileId,
          pdf_file_path: pdfUrl,
        } as Record<string, unknown>)
        if (versionErr) throw versionErr
      }
      void loadData()
      setCaricaPianoOpen(false)
      setCaricaPianoAthleteId('')
      setCaricaPianoFile(null)
    } catch (e) {
      logger.error('Carica piano PDF', e)
      setCaricaPianoError(e instanceof Error ? e.message : 'Errore caricamento piano')
    } finally {
      setCaricaPianoLoading(false)
    }
  }, [caricaPianoAthleteId, caricaPianoFile, profileId, orgId, supabase, loadData])

  const handleUnassignedRename = useCallback(async () => {
    if (!unassignedRenameRow?.storagePath || !unassignedRenameValue.trim()) return
    const base = unassignedRenameRow.storagePath.replace(/\/[^/]+$/, '')
    const newName =
      unassignedRenameValue
        .trim()
        .replace(/\.pdf$/i, '')
        .replace(/[/\\]/g, '-') + '.pdf'
    const toPath = `${base}/${newName}`
    setUnassignedRenameLoading(true)
    try {
      const { error: copyErr } = await supabase.storage
        .from('documents')
        .copy(unassignedRenameRow.storagePath, toPath)
      if (copyErr) throw copyErr
      await supabase.storage.from('documents').remove([unassignedRenameRow.storagePath])
      setUnassignedRenameRow(null)
      void loadData()
    } catch (e) {
      logger.error('Rinomina documento', e)
    } finally {
      setUnassignedRenameLoading(false)
    }
  }, [unassignedRenameRow, unassignedRenameValue, supabase, loadData])

  const handleUnassignedAssign = useCallback(async () => {
    if (!unassignedAssignRow?.storagePath || !unassignedAssignAthleteId || !orgId || !profileId)
      return
    setUnassignedAssignError(null)
    const fileName =
      unassignedAssignRow.fileName ??
      unassignedAssignRow.storagePath.split('/').pop() ??
      'piano.pdf'
    const toPath = `nutrition-plans/${unassignedAssignAthleteId}/${fileName}`
    setUnassignedAssignLoading(true)
    try {
      const { error: copyErr } = await supabase.storage
        .from('documents')
        .copy(unassignedAssignRow.storagePath, toPath)
      if (copyErr) {
        logger.error('Assegna documento: copy storage', copyErr)
        throw new Error(copyErr.message ?? 'Copia file non riuscita')
      }
      const pdfUrl = supabase.storage.from('documents').getPublicUrl(toPath).data.publicUrl
      let groupId: string
      const { data: existingGroup, error: groupSelectErr } = await nutritionFrom(
        supabase,
        NUTRITION_TABLES.planGroups,
      )
        .select('id')
        .eq('athlete_id', unassignedAssignAthleteId)
        .limit(1)
        .maybeSingle()
      if (groupSelectErr) {
        logger.error('Assegna documento: select group', groupSelectErr)
        throw new Error(groupSelectErr.message ?? 'Lettura gruppi fallita')
      }
      const groupRow = existingGroup as { id: string } | null
      if (groupRow?.id) {
        groupId = groupRow.id
      } else {
        const { data: newGroup, error: groupErr } = await nutritionFrom(
          supabase,
          NUTRITION_TABLES.planGroups,
        )
          .insert({
            athlete_id: unassignedAssignAthleteId,
            org_id: orgId,
            nutrizionista_id: profileId,
            title: (unassignedAssignRow.fileName ?? 'Piano').replace(/\.pdf$/i, '') || 'Piano',
          } as Record<string, unknown>)
          .select('id')
          .single()
        if (groupErr || !newGroup) {
          logger.error('Assegna documento: insert group', groupErr)
          throw new Error(groupErr?.message ?? 'Creazione gruppo fallita')
        }
        groupId = (newGroup as { id: string }).id
      }
      const { data: maxVer } = await nutritionFrom(supabase, NUTRITION_TABLES.planVersions)
        .select('version_number')
        .eq('plan_id', groupId)
        .order('version_number', { ascending: false })
        .limit(1)
        .maybeSingle()
      const nextVersion = (maxVer as { version_number: number | null } | null)?.version_number ?? 0
      const today = new Date().toISOString().slice(0, 10)
      const { error: versionErr } = await nutritionFrom(
        supabase,
        NUTRITION_TABLES.planVersions,
      ).insert({
        plan_id: groupId,
        org_id: orgId,
        version_number: nextVersion + 1,
        status: 'published',
        start_date: today,
        end_date: today,
        created_by: profileId,
        pdf_file_path: pdfUrl,
      } as Record<string, unknown>)
      if (versionErr) {
        logger.error('Assegna documento: insert version', versionErr)
        throw new Error(versionErr.message ?? 'Creazione versione fallita')
      }
      await supabase.storage.from('documents').remove([unassignedAssignRow.storagePath])
      setUnassignedAssignRow(null)
      setUnassignedAssignAthleteId('')
      setUnassignedAssignError(null)
      void loadData()
    } catch (e) {
      const msg = e instanceof Error ? e.message : "Errore durante l'assegnazione"
      setUnassignedAssignError(msg)
      logger.error('Assegna documento', e)
    } finally {
      setUnassignedAssignLoading(false)
    }
  }, [unassignedAssignRow, unassignedAssignAthleteId, orgId, profileId, supabase, loadData])

  const handleUnassignedDelete = useCallback(async () => {
    if (!unassignedDeleteRow?.storagePath) return
    setUnassignedDeleteLoading(true)
    try {
      const { error } = await supabase.storage
        .from('documents')
        .remove([unassignedDeleteRow.storagePath])
      if (error) throw error
      setUnassignedDeleteRow(null)
      void loadData()
    } catch (e) {
      logger.error('Elimina documento non assegnato', e)
    } finally {
      setUnassignedDeleteLoading(false)
    }
  }, [unassignedDeleteRow, supabase, loadData])

  const canEditValidity = useCallback(
    (r: VersionRow) => !!r.versionId && !r.versionId.startsWith('storage-'),
    [],
  )
  const openValidityEdit = useCallback((r: VersionRow) => {
    const today = new Date().toISOString().slice(0, 10)
    setValidityEditRow(r)
    setValidityEditStart(r.startDate ?? today)
    setValidityEditEnd(r.endDate ?? today)
  }, [])
  const handleValiditySave = useCallback(async () => {
    if (
      !validityEditRow ||
      !canEditValidity(validityEditRow) ||
      !validityEditStart ||
      !validityEditEnd
    )
      return
    setValidityEditLoading(true)
    try {
      const { error } = await nutritionFrom(supabase, NUTRITION_TABLES.planVersions)
        .update({ start_date: validityEditStart, end_date: validityEditEnd })
        .eq('id', validityEditRow.versionId)
      if (error) throw error
      setValidityEditRow(null)
      void loadData()
    } catch (e) {
      logger.error('Aggiorna validità piano', e)
    } finally {
      setValidityEditLoading(false)
    }
  }, [validityEditRow, validityEditStart, validityEditEnd, supabase, loadData, canEditValidity])

  const clearFilters = useCallback(() => {
    setKpiFilter(null)
    setFilterStato('all')
    setFilterScadenza('all')
    setFilterAuto('all')
    setSearchInput('')
  }, [])

  const handleExportPdf = useCallback(async () => {
    if (filteredAndSorted.length === 0) return
    setPdfLoading(true)
    try {
      const data: ExportData = filteredAndSorted.map((r) => ({
        atleta: r.athleteName,
        email: r.athleteEmail ?? '',
        piano: r.groupId.slice(0, 8),
        versione: r.versionNumber != null ? `v${r.versionNumber}` : '',
        stato: r.status,
        inizio: r.startDate ?? '',
        fine: r.endDate ?? '',
        kcal: r.caloriesTarget ?? '',
        P: r.proteinTarget ?? '',
        C: r.carbTarget ?? '',
        F: r.fatTarget ?? '',
        pdf: r.pdfFilePath ? 'sì' : 'no',
        auto: r.autoGenerated ? 'sì' : 'no',
      }))
      const blob = await buildTabularExportPdfBlob('Piani nutrizionali', data)
      openPdfWithBlob(blob, `piani_nutrizione_${todayStr}.pdf`)
    } catch (e) {
      logger.error('Export PDF piani', e)
    } finally {
      setPdfLoading(false)
    }
  }, [filteredAndSorted, todayStr, setPdfLoading, openPdfWithBlob])

  const openNuovoPiano = useCallback(
    (athleteId: string) => {
      setNuovoPianoOpen(false)
      router.push(`/dashboard/nutrizionista/piani/nuovo?atleta=${athleteId}`)
    },
    [router],
  )

  const athleteOptionsForNuovo = assignedAthletes
  const athleteOptionsForVersione = useMemo(
    () =>
      [...new Set(rows.map((r) => r.athleteId))].map((id) => {
        const r = rows.find((x) => x.athleteId === id)
        return r ? { id: r.athleteId, name: r.athleteName } : { id, name: id.slice(0, 8) }
      }),
    [rows],
  )

  if (showLoader) {
    return (
      <div className={LOADING_CLASS}>
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary" />
      </div>
    )
  }

  return (
    <StaffContentLayout
      title="Piani nutrizionali"
      description="Piani nutrizionali: versioni, scadenze e struttura."
      theme="teal"
      actions={
        <>
          <Button
            variant="default"
            size="sm"
            className="bg-teal-600 hover:bg-teal-500 text-white"
            onClick={() => setNuovoPianoOpen(true)}
          >
            <FilePlus className="mr-1.5 h-4 w-4" />
            Nuovo piano
          </Button>
          <Button variant="outline" size="sm" onClick={() => setCaricaPianoOpen(true)}>
            <Upload className="mr-1.5 h-4 w-4" />
            Carica piano
          </Button>
          <Button variant="outline" size="sm" onClick={() => setNuovaVersioneOpen(true)}>
            <Copy className="mr-1.5 h-4 w-4" />
            Crea nuova versione
          </Button>
          <Button
            variant="outline"
            size="sm"
            onClick={() => void handleExportPdf()}
            disabled={filteredAndSorted.length === 0 || pdfLoading}
            aria-busy={pdfLoading}
          >
            <FileText className="mr-1.5 h-4 w-4" />
            Esporta PDF
          </Button>
          <Button
            variant="outline"
            size="sm"
            className="lg:hidden"
            onClick={() => setFiltersOpen(true)}
            aria-label="Filtri"
          >
            <Filter className="h-4 w-4" />
          </Button>
        </>
      }
    >
      {error && (
        <div className="rounded-xl border-2 border-red-500/40 bg-red-500/10 px-3 py-2.5 sm:px-4 sm:py-3 text-red-200 text-sm flex items-center justify-between flex-wrap gap-2">
          <span>{error}</span>
          <Button
            variant="outline"
            size="sm"
            className="min-h-[44px] touch-manipulation"
            onClick={() => void loadData()}
          >
            Riprova
          </Button>
        </div>
      )}

      {/* KPI Bar */}
      {!loading && (
        <div className="grid grid-cols-2 sm:grid-cols-5 gap-3">
          <KpiCard
            label="Piani attivi"
            value={kpiCounts.attivi}
            active={kpiFilter === 'attivi'}
            onClick={() => setKpiFilter('attivi')}
            icon={ClipboardList}
          />
          <KpiCard
            label="Bozze"
            value={kpiCounts.bozze}
            active={kpiFilter === 'bozze'}
            onClick={() => setKpiFilter('bozze')}
            icon={FileText}
          />
          <KpiCard
            label="In scadenza 7 gg"
            value={kpiCounts.inScadenza}
            active={kpiFilter === 'scadenza'}
            onClick={() => setKpiFilter('scadenza')}
            icon={CalendarClock}
          />
          <KpiCard
            label="Scaduti"
            value={kpiCounts.scaduti}
            active={kpiFilter === 'scaduti'}
            onClick={() => setKpiFilter('scaduti')}
            icon={AlertCircle}
          />
          <KpiCard
            label="Auto-generati"
            value={kpiCounts.autoGen}
            active={kpiFilter === 'auto'}
            onClick={() => setKpiFilter('auto')}
            icon={Sparkles}
          />
        </div>
      )}

      {/* Search + Sort + Filters */}
      <div className="flex flex-col sm:flex-row gap-3">
        <div className="relative flex-1">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-text-tertiary" />
          <Input
            type="text"
            placeholder="Cerca atleta, email o reason…"
            value={searchInput}
            onChange={(e) => setSearchInput(e.target.value)}
            className="pl-9 w-full min-h-[44px]"
          />
        </div>
        <div className="flex flex-wrap items-center gap-2">
          <select
            value={sortBy}
            onChange={(e) => setSortBy(e.target.value as SortOption)}
            className="min-h-[44px] rounded-lg bg-background-secondary border border-border text-sm text-text-primary px-3 min-w-[180px]"
          >
            {SORT_OPTIONS.map((o) => (
              <option key={o.value} value={o.value}>
                {o.label}
              </option>
            ))}
          </select>
          <Button
            variant="outline"
            size="sm"
            className="hidden lg:inline-flex"
            onClick={() => setFiltersOpen(true)}
          >
            <Filter className="mr-1.5 h-4 w-4" /> Filtri
          </Button>
          {hasActiveFilters && (
            <Button variant="ghost" size="sm" onClick={clearFilters}>
              <X className="mr-1 h-4 w-4" /> Reset
            </Button>
          )}
        </div>
      </div>

      {/* Filters Drawer */}
      <Drawer open={filtersOpen} onOpenChange={setFiltersOpen} side="right" size="md">
        <DrawerContent
          className="bg-background border-l border-border"
          onClose={() => setFiltersOpen(false)}
        >
          <DrawerHeader className="border-b border-border p-5 flex items-center justify-between">
            <span className="font-semibold">Filtri</span>
            <Button
              variant="ghost"
              size="icon"
              onClick={() => setFiltersOpen(false)}
              aria-label="Chiudi"
            >
              <X className="h-5 w-5" />
            </Button>
          </DrawerHeader>
          <DrawerBody className="p-5 space-y-6">
            <div>
              <Label className="text-text-secondary text-xs uppercase tracking-wider">
                Stato versione
              </Label>
              <div className="flex flex-wrap gap-2 mt-1">
                {(['all', 'draft', 'active', 'archived'] as const).map((v) => (
                  <button
                    key={v}
                    type="button"
                    onClick={() => setFilterStato(v)}
                    className={`rounded-full px-3 py-1.5 text-sm ${
                      filterStato === v
                        ? 'bg-emerald-500/20 text-emerald-400 border border-emerald-500/30'
                        : 'bg-background-secondary text-text-muted border border-border'
                    }`}
                  >
                    {v === 'all'
                      ? 'Tutti'
                      : v === 'draft'
                        ? 'Bozze'
                        : v === 'active'
                          ? 'Attivi'
                          : 'Archiviati'}
                  </button>
                ))}
              </div>
            </div>
            <div>
              <Label className="text-text-secondary text-xs uppercase tracking-wider">
                Scadenza
              </Label>
              <div className="flex flex-wrap gap-2 mt-1">
                {(['all', '7', '30', 'scaduto'] as const).map((v) => (
                  <button
                    key={v}
                    type="button"
                    onClick={() => setFilterScadenza(v)}
                    className={`rounded-full px-3 py-1.5 text-sm ${
                      filterScadenza === v
                        ? 'bg-emerald-500/20 text-emerald-400 border border-emerald-500/30'
                        : 'bg-background-secondary text-text-muted border border-border'
                    }`}
                  >
                    {v === 'all' ? 'Tutti' : v === '7' ? '7 gg' : v === '30' ? '30 gg' : 'Scaduto'}
                  </button>
                ))}
              </div>
            </div>
            <div>
              <Label className="text-text-secondary text-xs uppercase tracking-wider">
                Auto-generato
              </Label>
              <div className="flex flex-wrap gap-2 mt-1">
                {(['all', 'si', 'no'] as const).map((v) => (
                  <button
                    key={v}
                    type="button"
                    onClick={() => setFilterAuto(v)}
                    className={`rounded-full px-3 py-1.5 text-sm ${
                      filterAuto === v
                        ? 'bg-emerald-500/20 text-emerald-400 border border-emerald-500/30'
                        : 'bg-background-secondary text-text-muted border border-border'
                    }`}
                  >
                    {v === 'all' ? 'Tutti' : v === 'si' ? 'Sì' : 'No'}
                  </button>
                ))}
              </div>
            </div>
            <Button variant="outline" className="w-full" onClick={clearFilters}>
              Azzera filtri
            </Button>
          </DrawerBody>
        </DrawerContent>
      </Drawer>

      {/* Content */}
      {loading ? null : rows.length === 0 ? (
        <div className="rounded-xl border border-border bg-background-secondary/50 px-4 py-12 text-center">
          <ClipboardList className="h-12 w-12 text-amber-400 mx-auto mb-3" />
          <p className="text-text-primary font-medium">Nessun piano trovato</p>
          <p className="text-text-secondary text-sm mt-1">
            Crea un piano dalla dashboard o dal profilo atleta.
          </p>
          <div className="flex flex-wrap justify-center gap-2 mt-4">
            <Button variant="default" size="sm" onClick={() => setNuovoPianoOpen(true)}>
              Nuovo piano
            </Button>
            <Link href="/dashboard/nutrizionista/atleti">
              <Button variant="outline" size="sm">
                Vai a Atleti
              </Button>
            </Link>
          </div>
        </div>
      ) : filteredAndSorted.length === 0 ? (
        <div className="rounded-xl border border-border bg-background-secondary/50 px-4 py-8 text-center">
          <p className="text-text-secondary text-sm">Nessun risultato per i filtri selezionati.</p>
          <Button variant="outline" size="sm" className="mt-3" onClick={clearFilters}>
            Reset filtri
          </Button>
        </div>
      ) : (
        <div className="rounded-xl border border-border overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead className="bg-background-tertiary/50 border-b border-border">
                <tr className="text-left text-text-secondary">
                  <th className="p-3 font-medium">Assegnato a</th>
                  <th className="p-3 font-medium">Piano / File</th>
                  <th className="p-3 font-medium">Versione</th>
                  <th className="p-3 font-medium">Stato</th>
                  <th className="p-3 font-medium">Validità</th>
                  <th className="p-3 font-medium">Macro</th>
                  <th className="p-3 font-medium w-10">PDF</th>
                  <th className="p-3 font-medium w-10">Auto</th>
                  <th className="p-3 font-medium w-24">Azioni</th>
                </tr>
              </thead>
              <tbody>
                {filteredAndSorted.map((r) => {
                  const isScaduto = r.endDate && r.endDate < todayStr
                  const scadeIn7 = r.endDate && r.endDate >= todayStr && r.endDate <= in7
                  return (
                    <tr
                      key={r.versionId}
                      className="border-b border-border/50 hover:bg-background-tertiary/30"
                    >
                      <td className="p-3">
                        <div>
                          <p
                            className={`font-medium ${r.isUnassigned ? 'text-text-muted' : 'text-text-primary'}`}
                          >
                            {r.athleteName}
                          </p>
                          {!r.isUnassigned && r.athleteEmail && (
                            <a
                              href={`mailto:${r.athleteEmail}`}
                              className="text-xs text-text-muted hover:text-emerald-400 inline-flex items-center gap-1"
                            >
                              <Mail className="h-3 w-3" />
                              {r.athleteEmail}
                            </a>
                          )}
                        </div>
                      </td>
                      <td className="p-3 text-text-muted font-mono text-xs">
                        {r.fileName ?? (r.groupId ? `${r.groupId.slice(0, 8)}…` : '—')}
                      </td>
                      <td className="p-3 font-medium text-text-primary">
                        {r.storagePath && r.versionNumber == null
                          ? 'Documento'
                          : `v${r.versionNumber ?? '—'}`}
                      </td>
                      <td className="p-3">
                        <span
                          className={`rounded-full px-2 py-0.5 text-xs ${
                            isRowActive(r)
                              ? 'bg-emerald-500/20 text-emerald-400'
                              : r.status === PLAN_VERSION_STATUS_DRAFT
                                ? 'bg-amber-500/20 text-amber-400'
                                : 'bg-background-elevated text-text-muted'
                          }`}
                        >
                          {isRowActive(r)
                            ? r.storagePath
                              ? 'Documento'
                              : 'Attivo'
                            : r.status === PLAN_VERSION_STATUS_DRAFT
                              ? 'Bozza'
                              : r.status}
                        </span>
                      </td>
                      <td className="p-3 text-text-muted">
                        <div className="flex items-center gap-1.5">
                          <span
                            className={
                              isScaduto ? 'text-red-400' : scadeIn7 ? 'text-amber-400' : ''
                            }
                          >
                            {r.startDate && r.endDate
                              ? `${new Date(r.startDate).toLocaleDateString('it-IT', { day: '2-digit', month: 'short' })} → ${new Date(r.endDate).toLocaleDateString('it-IT', { day: '2-digit', month: 'short', year: 'numeric' })}`
                              : '—'}
                          </span>
                          {canEditValidity(r) && (
                            <button
                              type="button"
                              onClick={() => openValidityEdit(r)}
                              className="p-1 rounded hover:bg-background-tertiary text-text-tertiary hover:text-primary"
                              title="Modifica date validità"
                              aria-label="Modifica date validità"
                            >
                              <Pencil className="h-3.5 w-3.5" />
                            </button>
                          )}
                        </div>
                      </td>
                      <td className="p-3 text-text-muted text-xs">
                        {r.caloriesTarget != null ? `${r.caloriesTarget} kcal` : '—'}
                        {(r.proteinTarget != null ||
                          r.carbTarget != null ||
                          r.fatTarget != null) && (
                          <span className="block text-text-tertiary">
                            P{r.proteinTarget ?? '—'} C{r.carbTarget ?? '—'} F{r.fatTarget ?? '—'}
                          </span>
                        )}
                      </td>
                      <td className="p-3">
                        {(() => {
                          const storagePath =
                            r.storagePath ??
                            (r.pdfFilePath && r.pdfFilePath.includes('/documents/')
                              ? r.pdfFilePath.split('/documents/')[1]
                              : r.pdfFilePath && r.pdfFilePath.startsWith('nutrition-plans/')
                                ? r.pdfFilePath
                                : null)
                          const fileName =
                            r.fileName ?? storagePath?.split('/').pop() ?? 'piano.pdf'
                          const hasFullUrl =
                            r.pdfFilePath &&
                            (r.pdfFilePath.startsWith('http://') ||
                              r.pdfFilePath.startsWith('https://'))
                          if (!storagePath && !hasFullUrl) {
                            return (
                              <span className="text-text-tertiary" title="Nessun PDF">
                                —
                              </span>
                            )
                          }
                          if (storagePath) {
                            return (
                              <DropdownMenu>
                                <DropdownMenuTrigger asChild>
                                  <button
                                    type="button"
                                    className="inline-flex text-emerald-400 hover:text-emerald-300 focus:outline-none focus:ring-2 focus:ring-primary/30 rounded p-0.5"
                                    title="PDF"
                                  >
                                    <FileText className="h-4 w-4" />
                                  </button>
                                </DropdownMenuTrigger>
                                <DropdownMenuContent align="end">
                                  <DropdownMenuItem
                                    onClick={() => {
                                      window.open(
                                        storagePreviewHref('documents', storagePath),
                                        '_blank',
                                        'noopener,noreferrer',
                                      )
                                    }}
                                  >
                                    <FileText className="h-4 w-4 mr-2" />
                                    Apri in nuova scheda
                                  </DropdownMenuItem>
                                  <DropdownMenuItem
                                    onClick={() => {
                                      void downloadStorageBlobViaPreview(
                                        'documents',
                                        storagePath,
                                        fileName,
                                      )
                                    }}
                                  >
                                    <Download className="h-4 w-4 mr-2" />
                                    Scarica
                                  </DropdownMenuItem>
                                </DropdownMenuContent>
                              </DropdownMenu>
                            )
                          }
                          if (hasFullUrl) {
                            return (
                              <a
                                href={r.pdfFilePath!}
                                target="_blank"
                                rel="noopener noreferrer"
                                className="inline-flex text-emerald-400 hover:text-emerald-300"
                                title="Apri PDF"
                              >
                                <FileText className="h-4 w-4" />
                              </a>
                            )
                          }
                          return (
                            <span className="text-text-tertiary" title="Nessun PDF">
                              —
                            </span>
                          )
                        })()}
                      </td>
                      <td className="p-3">
                        {r.autoGenerated ? (
                          <span className="rounded px-1.5 py-0.5 text-xs bg-purple-500/20 text-purple-400">
                            AUTO
                          </span>
                        ) : (
                          '—'
                        )}
                      </td>
                      <td className="p-3">
                        <div className="flex items-center gap-1">
                          {r.isUnassigned ? (
                            <DropdownMenu>
                              <DropdownMenuTrigger asChild>
                                <Button
                                  variant="ghost"
                                  size="icon"
                                  className="h-8 w-8 shrink-0"
                                  aria-label="Azioni documento"
                                >
                                  <MoreVertical className="h-4 w-4" />
                                </Button>
                              </DropdownMenuTrigger>
                              <DropdownMenuContent align="end">
                                <DropdownMenuItem
                                  onClick={() => {
                                    setUnassignedRenameRow(r)
                                    setUnassignedRenameValue(
                                      (r.fileName ?? '').replace(/\.pdf$/i, ''),
                                    )
                                  }}
                                >
                                  <Pencil className="h-4 w-4 mr-2" />
                                  Rinomina
                                </DropdownMenuItem>
                                <DropdownMenuItem
                                  onClick={() => {
                                    setUnassignedAssignRow(r)
                                    setUnassignedAssignAthleteId('')
                                    setUnassignedAssignError(null)
                                  }}
                                >
                                  <User className="h-4 w-4 mr-2" />
                                  Assegna a cliente
                                </DropdownMenuItem>
                                <DropdownMenuItem
                                  className="text-red-400 focus:text-red-400"
                                  onClick={() => setUnassignedDeleteRow(r)}
                                >
                                  <Trash2 className="h-4 w-4 mr-2" />
                                  Elimina
                                </DropdownMenuItem>
                              </DropdownMenuContent>
                            </DropdownMenu>
                          ) : (
                            <>
                              <Link
                                href={`/dashboard/nutrizionista/atleti/${r.athleteId}?tab=piani`}
                                className="text-emerald-400 hover:text-emerald-300 text-sm font-medium inline-flex items-center gap-1"
                              >
                                Apri <ArrowRight className="h-3.5 w-3.5" />
                              </Link>
                              <VersionRowActions row={r} onViewReason={setReasonModalRow} />
                            </>
                          )}
                        </div>
                      </td>
                    </tr>
                  )
                })}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* Modal Nuovo piano: scegli atleta */}
      <Dialog open={nuovoPianoOpen} onOpenChange={setNuovoPianoOpen}>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle>Nuovo piano — Seleziona atleta</DialogTitle>
          </DialogHeader>
          <div className="max-h-[60vh] overflow-y-auto space-y-1 py-2">
            {athleteOptionsForNuovo.length === 0 ? (
              <p className="text-text-muted text-sm">
                Nessun atleta assegnato. Gestisci le assegnazioni da Atleti.
              </p>
            ) : (
              athleteOptionsForNuovo.map((a) => (
                <button
                  key={a.id}
                  type="button"
                  onClick={() => openNuovoPiano(a.id)}
                  className="w-full text-left px-3 py-2 rounded-lg hover:bg-background-tertiary text-text-primary flex items-center justify-between gap-2"
                >
                  <span>{a.name}</span>
                  <ArrowRight className="h-4 w-4 text-text-muted shrink-0" />
                </button>
              ))
            )}
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setNuovoPianoOpen(false)}>
              Annulla
            </Button>
            <Button asChild>
              <Link href="/dashboard/nutrizionista/piani/nuovo">
                Crea senza atleta (assegna dopo)
              </Link>
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Modal Crea nuova versione: scegli atleta → profilo piani */}
      <Dialog open={nuovaVersioneOpen} onOpenChange={setNuovaVersioneOpen}>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle>Crea nuova versione — Seleziona atleta</DialogTitle>
          </DialogHeader>
          <div className="max-h-[60vh] overflow-y-auto space-y-1 py-2">
            {athleteOptionsForVersione.length === 0 ? (
              <p className="text-text-muted text-sm">
                Nessun atleta con piani. Crea prima un piano.
              </p>
            ) : (
              athleteOptionsForVersione.map((a) => (
                <button
                  key={a.id}
                  type="button"
                  onClick={() => {
                    setNuovaVersioneOpen(false)
                    router.push(`/dashboard/nutrizionista/atleti/${a.id}?tab=piani`)
                  }}
                  className="w-full text-left px-3 py-2 rounded-lg hover:bg-background-tertiary text-text-primary flex items-center justify-between gap-2"
                >
                  <span>{a.name}</span>
                  <ArrowRight className="h-4 w-4 text-text-muted shrink-0" />
                </button>
              ))
            )}
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setNuovaVersioneOpen(false)}>
              Annulla
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Modal Carica piano: atleta (opzionale) + PDF */}
      <Dialog
        open={caricaPianoOpen}
        onOpenChange={(open) => {
          if (!open) {
            setCaricaPianoOpen(false)
            setCaricaPianoAthleteId('')
            setCaricaPianoFile(null)
            setCaricaPianoError(null)
          }
        }}
      >
        <DialogContent className="max-w-md rounded-2xl">
          <DialogHeader className="space-y-1 pb-2">
            <DialogTitle className="text-xl font-semibold flex items-center gap-2">
              <span className="flex h-9 w-9 items-center justify-center rounded-lg bg-primary/10 text-primary">
                <Upload className="h-5 w-5" />
              </span>
              Carica piano
            </DialogTitle>
            <p className="text-sm text-text-muted">
              Carica un PDF come piano nutrizionale. Puoi assegnarlo subito a un atleta o in
              seguito.
            </p>
          </DialogHeader>
          <div className="space-y-5 py-2">
            {caricaPianoError && (
              <div className="flex items-center gap-2 rounded-lg border border-red-500/30 bg-red-500/10 px-3 py-2.5 text-sm text-red-400">
                <AlertCircle className="h-4 w-4 shrink-0" />
                {caricaPianoError}
              </div>
            )}
            <div className="space-y-2">
              <Label className="text-sm font-medium text-text-primary">
                Atleta <span className="font-normal text-text-muted">(opzionale)</span>
              </Label>
              <select
                value={caricaPianoAthleteId}
                onChange={(e) => setCaricaPianoAthleteId(e.target.value)}
                className="w-full min-h-[44px] rounded-xl border border-border bg-background-secondary/50 px-3 py-2.5 text-sm text-text-primary focus:border-primary/50 focus:outline-none focus:ring-1 focus:ring-primary/30"
              >
                <option value="">Nessuno — salva solo il PDF</option>
                {athleteOptionsForNuovo.map((a) => (
                  <option key={a.id} value={a.id}>
                    {a.name}
                  </option>
                ))}
              </select>
              {athleteOptionsForNuovo.length === 0 && (
                <p className="text-xs text-text-muted">
                  Nessun atleta assegnato. Il PDF verrà comunque salvato.
                </p>
              )}
            </div>
            <div className="space-y-2">
              <Label className="text-sm font-medium text-text-primary">File PDF</Label>
              <label className="flex flex-col gap-2 cursor-pointer">
                <div className="flex items-center gap-3 rounded-xl border border-dashed border-border bg-background-secondary/30 px-4 py-4 transition-colors hover:border-primary/40 hover:bg-background-secondary/50">
                  <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-primary/10 text-primary">
                    <FileText className="h-5 w-5" />
                  </div>
                  <div className="min-w-0 flex-1">
                    {caricaPianoFile ? (
                      <>
                        <p className="text-sm font-medium text-text-primary truncate">
                          {caricaPianoFile.name}
                        </p>
                        <p className="text-xs text-text-muted">Clicca per cambiare file</p>
                      </>
                    ) : (
                      <>
                        <p className="text-sm text-text-muted">Scegli un file PDF</p>
                        <p className="text-xs text-text-muted">max 50 MB</p>
                      </>
                    )}
                  </div>
                </div>
                <input
                  type="file"
                  accept=".pdf,application/pdf"
                  onChange={(e) => setCaricaPianoFile(e.target.files?.[0] ?? null)}
                  className="sr-only"
                />
              </label>
            </div>
          </div>
          <DialogFooter className="gap-2 pt-4 border-t border-border">
            <Button
              variant="outline"
              onClick={() => setCaricaPianoOpen(false)}
              disabled={caricaPianoLoading}
              className="min-h-[44px]"
            >
              Annulla
            </Button>
            <Button
              onClick={() => void handleCaricaPiano()}
              disabled={caricaPianoLoading || !caricaPianoFile}
              className="min-h-[44px] bg-teal-600 hover:bg-teal-500"
            >
              {caricaPianoLoading ? (
                <Loader2 className="h-4 w-4 animate-spin mr-1.5" />
              ) : (
                <Upload className="h-4 w-4 mr-1.5" />
              )}
              {caricaPianoLoading ? 'Caricamento...' : 'Carica piano'}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Modal Rinomina documento non assegnato */}
      <Dialog
        open={!!unassignedRenameRow}
        onOpenChange={(open) => !open && setUnassignedRenameRow(null)}
      >
        <DialogContent className="max-w-md rounded-2xl">
          <DialogHeader>
            <DialogTitle>Rinomina documento</DialogTitle>
          </DialogHeader>
          <div className="space-y-2 py-2">
            <Label className="text-sm font-medium text-text-primary">
              Nuovo nome file (senza .pdf)
            </Label>
            <Input
              value={unassignedRenameValue}
              onChange={(e) => setUnassignedRenameValue(e.target.value)}
              placeholder="es. Piano marzo 2026"
              className="min-h-[44px]"
              disabled={unassignedRenameLoading}
            />
          </div>
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setUnassignedRenameRow(null)}
              disabled={unassignedRenameLoading}
            >
              Annulla
            </Button>
            <Button
              onClick={() => void handleUnassignedRename()}
              disabled={unassignedRenameLoading || !unassignedRenameValue.trim()}
              className="min-h-[44px] bg-teal-600 hover:bg-teal-500"
            >
              {unassignedRenameLoading ? <Loader2 className="h-4 w-4 animate-spin mr-1.5" /> : null}
              Rinomina
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Modal Assegna documento a cliente */}
      <Dialog
        open={!!unassignedAssignRow}
        onOpenChange={(open) =>
          !open &&
          (setUnassignedAssignRow(null),
          setUnassignedAssignAthleteId(''),
          setUnassignedAssignError(null))
        }
      >
        <DialogContent className="max-w-md rounded-2xl">
          <DialogHeader>
            <DialogTitle>Assegna a cliente</DialogTitle>
            <p className="text-sm text-text-muted">
              Il documento verrà spostato tra i piani del cliente selezionato.
            </p>
          </DialogHeader>
          {unassignedAssignError && (
            <div className="rounded-lg border border-red-500/30 bg-red-500/10 px-3 py-2 text-sm text-red-400">
              {unassignedAssignError}
            </div>
          )}
          <div className="space-y-2 py-2">
            <Label className="text-sm font-medium text-text-primary">Cliente</Label>
            <select
              value={unassignedAssignAthleteId}
              onChange={(e) => setUnassignedAssignAthleteId(e.target.value)}
              className="w-full min-h-[44px] rounded-xl border border-border bg-background-secondary/50 px-3 py-2.5 text-sm text-text-primary focus:border-primary/50 focus:outline-none focus:ring-1 focus:ring-primary/30"
              disabled={unassignedAssignLoading}
            >
              <option value="">Seleziona cliente</option>
              {assignedAthletes.map((a) => (
                <option key={a.id} value={a.id}>
                  {a.name}
                </option>
              ))}
            </select>
            {assignedAthletes.length === 0 && (
              <p className="text-xs text-text-muted">
                Nessun atleta assegnato. Gestisci le assegnazioni da Atleti.
              </p>
            )}
          </div>
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => {
                setUnassignedAssignRow(null)
                setUnassignedAssignAthleteId('')
              }}
              disabled={unassignedAssignLoading}
            >
              Annulla
            </Button>
            <Button
              onClick={() => void handleUnassignedAssign()}
              disabled={unassignedAssignLoading || !unassignedAssignAthleteId}
              className="min-h-[44px] bg-teal-600 hover:bg-teal-500"
            >
              {unassignedAssignLoading ? <Loader2 className="h-4 w-4 animate-spin mr-1.5" /> : null}
              Assegna
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Modal Elimina documento non assegnato */}
      <Dialog
        open={!!unassignedDeleteRow}
        onOpenChange={(open) => !open && setUnassignedDeleteRow(null)}
      >
        <DialogContent className="max-w-md rounded-2xl">
          <DialogHeader>
            <DialogTitle>Elimina documento</DialogTitle>
            <p className="text-sm text-text-muted">
              Il file &quot;{unassignedDeleteRow?.fileName ?? 'documento'}&quot; verrà eliminato
              definitivamente dallo storage. Questa azione non si può annullare.
            </p>
          </DialogHeader>
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setUnassignedDeleteRow(null)}
              disabled={unassignedDeleteLoading}
            >
              Annulla
            </Button>
            <Button
              variant="destructive"
              onClick={() => void handleUnassignedDelete()}
              disabled={unassignedDeleteLoading}
              className="min-h-[44px]"
            >
              {unassignedDeleteLoading ? (
                <Loader2 className="h-4 w-4 animate-spin mr-1.5" />
              ) : (
                <Trash2 className="h-4 w-4 mr-1.5" />
              )}
              {unassignedDeleteLoading ? 'Eliminazione...' : 'Elimina'}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Modal Modifica date validità */}
      <Dialog open={!!validityEditRow} onOpenChange={(open) => !open && setValidityEditRow(null)}>
        <DialogContent className="max-w-md rounded-2xl">
          <DialogHeader>
            <DialogTitle>Date validità</DialogTitle>
            <p className="text-sm text-text-muted">
              Imposta o modifica data inizio e scadenza del piano.
            </p>
          </DialogHeader>
          <div className="grid grid-cols-2 gap-4 py-2">
            <div className="space-y-2">
              <Label htmlFor="validity-start">Data inizio</Label>
              <Input
                id="validity-start"
                type="date"
                value={validityEditStart}
                onChange={(e) => setValidityEditStart(e.target.value)}
                disabled={validityEditLoading}
                className="min-h-[44px]"
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="validity-end">Data scadenza</Label>
              <Input
                id="validity-end"
                type="date"
                value={validityEditEnd}
                onChange={(e) => setValidityEditEnd(e.target.value)}
                disabled={validityEditLoading}
                className="min-h-[44px]"
              />
            </div>
          </div>
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setValidityEditRow(null)}
              disabled={validityEditLoading}
            >
              Annulla
            </Button>
            <Button
              onClick={() => void handleValiditySave()}
              disabled={validityEditLoading || !validityEditStart || !validityEditEnd}
              className="min-h-[44px] bg-teal-600 hover:bg-teal-500"
            >
              {validityEditLoading ? <Loader2 className="h-4 w-4 animate-spin mr-1.5" /> : null}
              {validityEditLoading ? 'Salvataggio...' : 'Salva'}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Modal Vedi reason (auto_adjustment_reason) */}
      <Dialog open={!!reasonModalRow} onOpenChange={(open) => !open && setReasonModalRow(null)}>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle>Motivo auto-aggiustamento</DialogTitle>
          </DialogHeader>
          {reasonModalRow && (
            <p className="text-text-secondary text-sm whitespace-pre-wrap">
              {reasonModalRow.autoAdjustmentReason ?? '—'}
            </p>
          )}
          <DialogFooter>
            <Button variant="outline" onClick={() => setReasonModalRow(null)}>
              Chiudi
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <PdfCanvasPreviewDialog
        open={pdfOpen}
        onOpenChange={onPdfOpenChange}
        blob={pdfBlob}
        filename={pdfFilename}
        title="Anteprima — Piani"
      />
    </StaffContentLayout>
  )
}
